parameters:
#    drp_registrar_admin.example.class: DRP\RegistrarAdminBundle\Example

services:
#    drp_registrar_admin.example:
#        class: %drp_registrar_admin.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
