parameters:
#    drp_user.example.class: DRP\UserBundle\Example

services:
#    drp_user.example:
#        class: %drp_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
