parameters:
#    drp_admin.example.class: DRP\AdminBundle\Example

services:
#    drp_admin.example:
#        class: %drp_admin.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
